### ISSUE TITLE
Pre-built?

### ISSUE THREAD

**Issue by mjcampagna** [rafgraph/detect-it#11]
Any chance you can include a pre-built version of the script, ready to be dropped into an existing HTML document via traditional <script /> tag?

**Comment by rafrex** [comment]
Yea I’ll add it to my todo list. Or you can make a PR adding a creat dist script. Probably makes sense to use Rollup. Don’t check in the dist directory. Once the script is ready I’ll publish a new version so dist is available from unpkg cdn.

**Comment by rsepierre** [comment]
Hi, this really seems like what we need to define our behaviour on websites.
Sadly same issue, I could not make it work.
Is it node.js ? regular javascript ? should I put the 'import' between <script> tags ? into a .js file ?

Tried to understand how it was working viewing the source on http://detect-it.rafrex.com/ but it was all minified in a bundle.js (I guess). Documentation and exemples on "import" is ridiculous online.

**Comment by rafrex** [comment]
You can see source code for example site in the `gh-pages` branch https://github.com/rafrex/detect-it/blob/gh-pages/src/index.js#L4

You need to transpile code with `import`s using babel. http://babeljs.io/

**Comment by quanghuyit** [comment]
Hi,
can it be used for wordpress?

**Comment by rafgraph** [comment]
v4 includes a pre-built option that you can load from the unpkg cdn.
For more info, see https://github.com/rafgraph/detect-it#pre-built-cdn-option
