### ISSUE TITLE
Test failed so hope this data can help you out 

### ISSUE THREAD

**Issue by etetlow** [rafgraph/detect-it#15]
I have a Dell Inspiron 5000 series with FHD touchscreen running MacOS 10,14,1. Have been looking for a way to detect touchscreens on clients devices for a project and came across this. Looks like a very thorough and thought out project but unfortunately failed with my Dell. Here's some data that may or may not help.

| Dell Inspiron 5000 MacOS 10,14,1 | Chrome 70.0.3538.110 | Chrome Canary 72.0.3619.0 | Firefox 63.0.3 | Opera 56.0.3051.104 | Safari 12.0.1 (14606.2.104.1.1) |
|:--------------------------------:|:--------------------:|:-------------------------:|:--------------:|:-------------------:|:-------------------------------:|
| deviceType: | mouse only | mouse only | mouse only | mouse only | mouse only |
| passiveEvents: | true | true | true | true | true |
| hasMouse: | true | true | true | true | true |
| hasTouch: | false | false | false | false | false |
| primaryInput: | mouse | mouse | mouse | mouse | mouse |
| hover: | true | true | false | true | true |
| none: | false | false | false | false | false |
| anyHover: | true | true | false | true | true |
| anyNone: | false | false | false | false | false |
| fine: | true | true | false | true | true |
| coarse: | false | false | false | false | false |
| none: | false | false | false | false | false |
| anyFine: | true | true | false | true | true |
| anyCoarse: | false | false | false | false | false |
| anyNone: | false | false | false | false | false |
| hasSupport: | false | false | false | false | false |
| browserSupportsApi: | true | true | false | true | false |
| hasSupport: | true | true | true | true | true |

I'm still searching for a reliable method but there just doesn't seem to be one so far. If you have any ideas or thoughts on this data, just give me a shout.

Thanks.

**Comment by rafgraph** [comment]
Sorry for the late reply, v4 of `detect-it` is in pre-release, if you are still using a touch screen with Mac OS I’d be interested what the current results are https://detect-it.rafgraph.dev

From looking at the above results, the browser isn’t identifying that it has a touch screen so there’s not much detect it can do. I’d be interested if TouchEvents or PointerEvents with `pointerType` `touch` are created by the browser when using the touch screen (it seems doubtful from the above results), so it might be a case of MacOS not properly supporting a touch screen (drivers etc).
