### ISSUE TITLE
Pointer Events

### ISSUE THREAD

**Issue by richardbushell** [rafgraph/detect-it#16]
Hi, thanks for this very useful library.

The v3 tests are reporting mouseOnly for a Touchscreen Laptop, isn't it now a good idea to re-introduce the Pointer Events into the test?

Can I Use is now at 75%:
https://caniuse.com/#feat=pointer

and WebKit has now JUST supported Pointer Events by default in their Technology Preview:
https://developer.apple.com/safari/technology-preview/release-notes/
(which should fill in most of the remaining percentages very shortly)

And it is now successfully used by:
https://patrickhlauke.github.io/touch/touchscreen-detection/

It would be great to add this back in from version 1 to version 3 to plug this gap in successful detections.

**Comment by rafrex** [comment]
Thanks for the comment, I think it may be time to add back Pointer Events detection, although I'm not sure it will help with your implied issue.

> The v3 tests are reporting mouseOnly for a Touchscreen Laptop, isn't it now a good idea to re-introduce the Pointer Events into the test?

I think you are implying that there is a browser that supports touch input through the pointer events api but not through the touch events api 🤔.. I'm am unaware of any browser that supports pointer events api but not the touch events api.. can you provide browser version and hardware info?

The v1 detection with pointer events can be found here: http://detect-it-v1.rafrex.com/#detect-pointer-events
What does the Detect Pointer Events section say? Thanks.

**Comment by rafgraph** [comment]
@richardbushell `detect-it` v4 is in pre-release and includes PointerEvents as well as improved device detection. Try it out with `npm install --save detect-it@next` or view the live detection test at https://detect-it.rafgraph.dev

**Comment by rafgraph** [comment]
v4 released with support for Pointer Events 🎉
