### ISSUE TITLE
Problem running on IE11

### ISSUE THREAD

**Issue by binhpv** [rafgraph/detect-it#24]
Hello @rafgraph,

First I would like to say thanks to the work you put in this repository. We have been relying on it since a few years and it work great.

However when I upgrade from v1 to v4, I have problem on IE11, which, sadly, is still required for our customer.

I tried to look for supported browser of this package but wasn't able to find the list. Do you have it document somewhere? If IE 11 is not supported at all I can stay with v1. If it is, I can try to find a fix and submit a PR.

Many thanks.

**Comment by rafgraph** [comment]
I'm not opposed to supporting IE 11. Nothing in the code jumps out at me as not IE 11 compatible (it is compiled to ES5 with no additional JS apis required). As long as the fix is small I'd be happy to merge a PR.

**Comment by binhpv** [comment]
Hi @rafgraph , could you have a look at my PR? Many thanks.

**Comment by rafgraph** [comment]
@binhpv I released v4.0.1 with the fix.
