### ISSUE TITLE
getting TypeError: Cannot read property 'maxTouchPoints' of undefined` in dev mode bundling

### ISSUE THREAD

**Issue by razi-ed** [rafgraph/detect-it#26]
node_modules/detect-it/dist/detect-it.cjs.development.js:39

var hasTouch = (w.navigator.maxTouchPoints || 0) > 0 || supportsTouchEvents;

 ^
 
TypeError: Cannot read property 'maxTouchPoints' of undefined`

**Comment by rafgraph** [comment]
Hi, I’m unable to reproduce this error. Can you provide more information for reproduction? What browser, etc... thanks. 

In order for this to error to occur there needs to be a `window` but no `window.navigator`.

**Comment by rafgraph** [comment]
Closing for now. Can reopen if info to reproduce is provided.
